// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkmoadoopwewyvobulri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbW9hZG9vcHdld3l2b2J1bHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjYzOTgsImV4cCI6MjA1Njk0MjM5OH0.HKteRY3oWAzge9vYEMiXIiZCCjd1hbi3kH5GzEY7elQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);